import type { PayloadAction } from '@reduxjs/toolkit'
import { createSlice } from '@reduxjs/toolkit'
//import { fetchCount } from './counterAPI'

export interface BufferState {
  buffer: any
}

const initialState: BufferState = {
  buffer: null
}

/// 資料交換緩衝區
export const bufferSlice = createSlice({
  name: 'buffer',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setBuffer: (state, action: PayloadAction<object>) => {
      state.buffer = { ...action.payload }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => { },
})

export const { setBuffer } = bufferSlice.actions

export default bufferSlice.reducer
